#!/bin/bash

if [ ! -d "$HOME/bin/" ]; then
    echo "~/bin/ is required"
    exit 1
fi

export PATH="$HOME/bin/:$PATH"

wget_bin()
{
    URL=$1
    BIN_NAME=$(basename $URL)
    DST_NAME=~/bin/$BIN_NAME

    if [ -x $DST_NAME ]; then
        return
    fi

    wget $URL -P ~/bin/
    chmod +x $DST_NAME
}

wget_bin "https://github.com/outscale-mgo/json-array-object/releases/download/0.1.0/json-array-x86_64.AppImage"
wget_bin "https://github.com/outscale-mgo/json-array-object/releases/download/0.1.0/json-object-x86_64.AppImage"
wget_bin "https://github.com/cosmo-ray/json-search/releases/download/0.1/json-search-x86_64.AppImage"

alias json-array=json-array-x86_64.AppImage
alias json-object=json-object-x86_64.AppImage
alias json-search=json-search-x86_64.AppImage

oscp_retrive_ak()
{
    TW=$(($(tput cols) - 4))
    RET=$( curl -s -X POST https://icu.eu-west-2.outscale.com \
	   -d $( json-object AuthenticationMethod  password Password $2 Login $1 ) \
	   -H 'x-amz-target:TinaIcuService.ListAccessKeys' )
    echo $RET | json-search accessKeys | ponysay -W$TW
}

oscp_list()
{
    TW=$(($(tput cols) - 4))
    curl -s -X POST https://api.eu-west-2.outscale.com/api/latest/Read$1 \
	 --user $OSC_ACCESS_KEY:$OSC_SECRET_KEY \
	 --aws-sigv4 "osc" | json-search $1 | ponysay -W$TW
}
